
SOURCE = Robot.cpp

LDFLAGS += -L/home/allen/Development/first/pixycam/libpixyusb/pixy/build/libpixyusb -lpixyusb -lboost_system -lboost_thread -lboost_chrono -lusb-1.0
CPPFLAGS += -I/home/allen/Development/first/pixycam/libpixyusb/pixy/src/host/libpixyusb/include -I/home/allen/Development/first/pixycam/libpixyusb/pixy/src/common/inc -I/usr/include/libusb-1.0

include ../include.mk
